---

- name: Add WireGuard PPA
  apt_repository:
    repo: ppa:wireguard/wireguard
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '<')

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ wireguard_apt_cache_valid_time }}"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install Linux kernel headers
  apt:
    name: linux-headers-amd64
  when: ansible_distribution == 'Debian'

- name: Install WireGuard (Ubuntu)
  apt:
    name: wireguard
  when: ansible_distribution == 'Ubuntu'

- name: Install WireGuard (Debian)
  apt:
    name: wireguard
    default_release: buster-backports
  when: ansible_distribution == 'Debian'
